### ISSUE TITLE
样式丢失

### ISSUE THREAD

**Issue by 562127386** [newbienewbie/InDirectLine#4]
哥们  我看你的网页例子样式咋丢失了啊，我测试运行也是这个情况。望指教

**Comment by newbienewbie** [comment]
@562127386 你说的是WebChat的情况吧，我之前也注意到了，应该是个bug（我之前写了主要用来测试微信公众号来着，所以也没修这块，没法自定义样式），晚点有空了我来修复一下 :)

**Comment by 562127386** [comment]
嗯 是的 我看了下WebChat.js 没找到方法，能力有限。 谢了  大牛

**Comment by newbienewbie** [comment]
目前了解下来，我代码示例里用的是未指定的Prompt Style。奇怪的是在BotFramework Emulator里显示为漂亮的样式，但是在WebChat.js里就不显示什么特定样式。

目前看下来，好像不是我这边InDirectLine的问题。如果我手工指定一个提示风格，比如`SuggestedAction`，
```csharp
async(ctx , ct)=>{
    var dialogTurnResult = await ctx.PromptAsync(DialogNames.ChoicePrompt,new PromptOptions{
        Choices = new List<Choice>{
            new Choice{
                Value = "A: 历史文章",
                Synonyms = new List<string>{
                    "A","历史","历史文章",
                },
            },
            new Choice{
                Value = "B: 笑话",
                Synonyms = new List<string>{
                    "B","笑话",
                },
            },
        },
        Style = ListStyle.SuggestedAction,         // 加上这一行，在WebChat.js里就显示 提示动作 的样式了
    });
    return dialogTurnResult;
},
```

在WebChat.js里显示是没有问题的：

![截图](https://user-images.githubusercontent.com/10741879/75258075-ec026880-5820-11ea-88fa-7108fba51f7d.png)


似乎WebChat.js对Choice Prompt 的默认Style支持就是这样的？（如果我错了，请纠正我）

@562127386  你有尝试过使用原生的Azure DirectLine而非这里的InDirectLine测吗？

**Comment by 562127386** [comment]
没在Azure 上测试过奥，我在乱换WebChat.js版本测试时，有一次在网页上显示样式了，可以单击选项。不清楚是缓存还是延迟的原因。后面想重现这种情况一直没重现。。。

**Comment by 562127386** [comment]
我在前端styleOptions加的样式会起作用的。如果能调试下webchat.js看下收到服务器端咋样处理的就好找原因了，不知道咋调试这个js。。

**Comment by 562127386** [comment]
我测试加上Style = ListStyle.SuggestedAction然后把IntegrationBotSample和Itminus.InDirectLine.Web两个应用发布到阿里云上我本机连接发现选择的几个内容都没有了，两个应用地址 http://47.98.59.155:3000/v3/directline/tokens/generate  和http://47.98.59.155:3000/v3/directline

**Comment by newbienewbie** [comment]
> 发现选择的几个内容都没有了

@562127386 请问选择的几个内容没有了是指什么？我看了下你这个IP暴露给用户的5000端口，似乎可以工作？

![截图](https://user-images.githubusercontent.com/10741879/75404325-2402cc00-5945-11ea-815d-84dd9d7bc922.png)

**Comment by newbienewbie** [comment]
@562127386  感觉像是你的服务器没有调用prompt，websocket都没收到后续消息：


![截图](https://user-images.githubusercontent.com/10741879/75404325-2402cc00-5945-11ea-815d-84dd9d7bc922.png)

方便贴一下你的服务端代码吗？

**Comment by 562127386** [comment]
收到了 。你盲输入 a b 你就看到回复了。我服务器端没有改代码。

**Comment by newbienewbie** [comment]
@562127386 我的意思是 浏览器端并没有收到消息，所有往来的消息都可以在WebSocket连接里看到的。你使用Docker部署的吗?还是手工部署的？服务端日志可否贴一下？

**Comment by 562127386** [comment]
手工IIS部署的 ，你方便有个联系方式不 我可以把服务器用户密码发给你登录调试下。这边截图还上传不到github上

**Comment by newbienewbie** [comment]
@562127386 
1. 请不要给我发服务器的相关密码，也不要给其他人发。我建议是在你的服务器上安装Docker，手工部署是给自己找麻烦啊。
2. 至于联系方式，我的邮箱账号 itminus@hotmail.com。微信等联系方式暂时不太方便在这里公开，如果确实需要，请先给我发一份邮件，并且正文中请务必包含“562127386@GitHub”字样。
